{
 "title": "APM for OpenTelemetry",
 "description": "APM dashboard for monitoring OpenTelemetry-based services.  \n\nInstrument your applications using OpenTelemetry SDKs and send traces, metrics, and logs to Tempo for traces, a Prometheus-compatible database like Mimir for metrics, and Loki for logs. This dashboard provides a centralized view of your application's health and performance.  \n\nFor a fully managed observability stack, consider using Grafana Cloud.  \n\nLearn more about this dashboard on https://github.com/cyrille-leclerc/opentelemetry-service-dashboard.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "deployment_environment_name",
    "label": "Environment",
    "query": {
     "query": "label_values(target_info,deployment_environment_name)"
    }
   },
   {
    "name": "service_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info{deployment_environment_name=~\"$deployment_environment_name\"},service_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "Name",
    "query": {
     "query": "label_values(target_info{service_namespace=~\"$service_namespace\", deployment_environment_name=~\"$deployment_environment_name\"},exported_job)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "description": "service.namespace=${service_namespace}, service.name=${service_name}, deployment.environment.name=${deployment_environment_name}",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><img src=\"https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png\" alt=\"OpenTelemetry Icon\" width=\"25\" height=\"\"> Service: ${service_namespace}/${service_name} env: ${deployment_environment_name}</h1>\n"
   }
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received in the past 24h.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(sum by (deployment_environment_name, service_namespace, exported_job) (target_info{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", exported_job=\"$service_name\"}) or absent{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Response Time",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, namespace, exported_job) (rate(http_server_request_duration_seconds_bucket{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, namespace, exported_job) (rate(http_server_request_duration_seconds_bucket{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "avg by(namespace, exported_job) (rate(http_server_request_duration_seconds_sum{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval])) / avg by(namespace, exported_job) (rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Server Requests (rate)",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval])) by (namespace, exported_job)) ",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "description": "HTTP endpoints aggregation on the `http.server.request.duration` metric. \n\nErrors are identified by   `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(namespace, exported_job) (rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval])) * 100) / sum by(namespace, exported_job) (rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Operations (inbound) e Dependencies (outbound)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Operations",
     "type": "table",
     "description": "Inbound HTTP operations of the service (aka HTTP endpoints) based on the `http.server.request.duration` metric.\n\nErrors are identified by `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "avg_over_time(\n  sum by (operation) (\n    label_join(\n      rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n      \"operation\",\n      \" \",\n      \"http_request_method\",\n      \"http_route\"\n    )\n  )[5m:]\n)",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    )",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "\n        histogram_quantile(\n            0.99,\n            sum by (le, operation) (\n                label_join(\n                rate(http_server_request_duration_seconds_bucket{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[5m]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n                )\n            )\n        )\n    ",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Outbound HTTP Services",
     "type": "table",
     "description": "Performance - Dependencies",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "avg_over_time(\nsum by (outbound_service) (\n    label_join(\n        rate(http_client_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n    )\n  )[5m:]\n)",
       "legendFormat": "HTTP: {{http_request_method}} {{server_address}}"
      },
      {
       "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    )",
       "legendFormat": "HTTP: {{http_request_method}} {{server_address}}"
      },
      {
       "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_request_duration_seconds_bucket{namespace=~\"$service_namespace\", exported_job=\"$service_name\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n        )\n    )\n)",
       "legendFormat": "HTTP: {{http_request_method}} {{server_address}}"
      }
     ]
    },
    {
     "title": "Requests statistics",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_route=~\".*\", \n  http_route!=\"/healthz\", \n  http_route!=\"\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000",
       "legendFormat": "x"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_response_status_code=~\"2..\", \n  http_route=~\".*\", \n  http_route!=\"/healthz\", \n  http_route!=\"\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000\n",
       "legendFormat": "x"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_response_status_code=~\"3..\", \n  http_route=~\".*\", \n  http_route!~\"/healthz|^$\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000\n",
       "legendFormat": "x"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_response_status_code=~\"4..\", \n  http_route=~\".*\", \n  http_route!~\"/healthz|^$\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000\n",
       "legendFormat": "x"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_response_status_code=~\"5..\", \n  http_route=~\".*\", \n  http_route!~\"/healthz|^$\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000\n",
       "legendFormat": "x"
      },
      {
       "expr": "sum(rate(http_server_request_duration_seconds_sum{\n  exported_job=~\"$service_name\", \n  http_request_method=~\".*\", \n  http_route=~\".*\", \n  http_route!~\"/healthz|^$\"\n}[5m])) by (exported_job, http_request_method, http_route) * $__interval_ms / 1000\n",
       "legendFormat": "x"
      },
      {
       "expr": "(\n  sum(rate(http_server_request_duration_seconds_sum{\n    exported_job=~\"$service_name\", \n    http_request_method=~\".*\", \n    http_route=~\".*\", \n    http_route!~\"/healthz|^$\"\n  }[5m])) by (exported_job, http_request_method, http_route) \n  / \n  sum(rate(http_server_request_duration_seconds_count{\n    exported_job=~\"$service_name\", \n    http_request_method=~\".*\", \n    http_route=~\".*\", \n    http_route!~\"/healthz|^$\"\n  }[5m])) by (exported_job, http_request_method, http_route) \n  >= 0\n) OR on() vector(0)",
       "legendFormat": "x"
      }
     ]
    }
   ]
  },
  {
   "title": "Traces - Grafana Tempo.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Traces containing a span emitted by the service",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 215 },
     "targets": [
      {
       "filters": [
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "$service_name" ],
         "valueType": "string"
        },
        {
         "id": "6997e808",
         "operator": "=",
         "scope": "resource",
         "tag": "deployment.environment.name",
         "value": [ "$deployment_environment_name" ],
         "valueType": "string"
        },
        {
         "id": "e9f0e855",
         "operator": "=",
         "scope": "resource",
         "tag": "service.namespace",
         "value": [ "$service_namespace" ],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$service_name\" && resource.k8s.namespace.name=\"$service_namespace\" && span.http.response.status_code!=202 && span.http.response.status_code!=204 && span.http.response.status_code!=200} | select(span.url.path, span.server.address, span.http.response.status_code)",
       "tableType": "spans"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs (em desenvolvimento).",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "description": "Logs of the service, filtered by `service.name` and `service.namespace`.\n\nTo explore the logs, open the menu clicking on the icon `⋮` of this panel and click on `Explore`.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 366 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{deployment_environment_name=~\"$deployment_environment_name\", service_namespace=~\"$service_namespace\", service_name=\"$service_name\"} | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .service_instance_id}}{{if .thread_name}}/{{alignRight 20 .thread_name}}{{else if eq \"java\" .telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .scope_name }}{{alignRight 40 .scope_name}}{{end}}{{if .exception_type}} \u001b[1;101m \u001b[0m{{end}} {{if .exception_type}}\u001b[1;91m{{.exception_type}}\u001b[0m{{end}}{{if .exception_message}} \u001b[1;91m{{.exception_message}}\u001b[0m {{end}} \u001b[0m {{__line__}} {{if .trace_id}} \u001b[37m\u001b[3m[trace_id={{.trace_id}}]{{end}}`"
      }
     ]
    }
   ]
  }
 ]
}